#!/usr/bin/perl -w

use esmith::Build::CreateLinks  qw(:all);

# Templates to expand
templates2events("/etc/e-smith/sql/init/tt-rss", qw(bootstrap-console-save webapps-update));
templates2events("/usr/share/tt-rss/config.php", qw(bootstrap-console-save webapps-update));
templates2events("/etc/cron.d/tt-rss", qw(bootstrap-console-save webapps-update));

# tt-rss daemon
safe_symlink("restart", "root/etc/e-smith/events/webapps-update/services2adjust/tt-rss");
safe_symlink("../daemontools" , 'root/etc/rc.d/init.d/supervise/tt-rss');
safe_symlink("/var/service/tt-rss" , 'root/service/tt-rss');
safe_touch("root/var/service/tt-rss/down");
service_link_enhanced("tt-rss", "S98", "7");
service_link_enhanced("tt-rss", "K10", "6");
service_link_enhanced("tt-rss", "K10", "0");


# PHP header and footer
safe_symlink("/etc/e-smith/templates-default/template-begin-php", "root/etc/e-smith/templates/usr/share/tt-rss/config.php/template-begin");
safe_symlink("/etc/e-smith/templates-default/template-end-php", "root/etc/e-smith/templates/usr/share/tt-rss/config.php/template-end");

